default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['MPS_DB_USER'] %>
  password: <%= ENV['MPS_DB_PASSWORD'] %>
  database: <%= ENV['MPS_DB_NAME'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['MPS_DB_IP'] %>

test:
  <<: *default
  host: <%= ENV['MPS_DB_TEST_IP'] %>

production:
  <<: *default
