source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.11.0'
# Prawn pdf
gem 'prawn', '~> 2.2.2'
# Pagination for models
gem 'kaminari-core', '~> 1.1.1'
gem 'kaminari-activerecord', '~> 1.1.1'

group :development do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.7', '>= 3.7.2'
end
